set history=1000
set viminfo^=% "Remeber open buffers on close
set autoread
set autowrite
set timeoutlen=250
set backspace=eol,start,indent
"set cursorline
"set list
"set listchars=tab:▸\ ,eol:¬
set encoding=utf8
set fencs=ucs-bom,utf-8,defeault,latin,cp936,gb2312
set ffs=unix,dos,mac
set hlsearch
set ignorecase
set incsearch
set linebreak
set magic         "Set magic on, for regular expressions
set showmatch     "Show matching bracets when text indicator is over them
set matchtime=2   "How many tenths of a second to show the matching paren
set modeline

set nobackup
set nowritebackup
set noswapfile
set number
set ruler         "Always show current position
set noerrorbells  "No sound on errors
set novisualbell
set vb t_vb=
set showmode
set smartcase
set scrolloff=7

"formatting
set textwidth=80
set smarttab
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set foldenable
set foldmethod=marker
set formatoptions=qrn1
set whichwrap+=<,>,h,l
set wrap

syntax enable

set hidden           "Change buffer - without saving
set nolazyredraw     "Don't redraw while executing macros
set ttyfast
set splitright

"commandline
set laststatus=2 "Always show the statusline
set wildmenu
set wildmode=list:longest
set gdefault
set cmdheight=2                                     

iab xdate <c-r>=strftime("%Y-%m-%d %H:%M:%S")<cr>

"Delete trailing white space, useful for Python ;)
func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc
autocmd BufWrite *.py :call DeleteTrailingWS()

set guitablabel=%t

"mappings/*{{{*/
let mapleader=","
let g:mapleader=","

"Remap VIM 0
map 0 ^
"Useful when moving accross long lines
map j gj
map k gk

"map <leader>c :botright cope<cr>
map <leader>n :cn<cr>
map <leader>p :cp<cr>

nnoremap <silent> <leader><cr> :noh<cr>

"Smart way to move btw. windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

"When pressing <leader>cd switch to the directory of the open buffer
map <leader>cd :cd %:p:h<cr>
map <leader>ce :cd ~/dev<cr>

"Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm
map <leader>pp :setlocal paste!<cr>
nnoremap <leader>e :e! $MYVIMRC<cr>
nnoremap <leader>ev <c-w><c-v><c-l>:e $MYVIMRC<cr>
nnoremap <leader>w <c-w>v<c-w>l
nmap <F12> :!ctags -R *<cr>

map <leader>ss :setlocal spell!<cr>
map <leader>sn ]s
map <leader>sp [s
map <leader>sa zg
map <leader>s? z="/*}}}*/

"Scripts and Bundles "/*{{{*/
set nocompatible
filetype off
set rtp+=$HOME/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

"general must-haves
Plugin 'thinca/vim-quickrun.git'
Plugin 'tpope/vim-repeat.git'
Plugin 'vim-scripts/VisIncr.git'
Plugin 'scrooloose/nerdcommenter.git'
Plugin 'tpope/vim-surround.git'
Plugin 'vim-scripts/matchit.zip.git'
Plugin 'Twinside/vim-cuteErrorMarker.git'
Plugin 'majutsushi/tagbar.git'
let g:tagbar_usearrows = 1
nnoremap <leader>l :TagbarToggle<CR>
Plugin 'ervandew/supertab.git'
Plugin 'godlygeek/tabular.git'
Plugin 'vim-scripts/YankRing.vim.git'
Plugin 'Raimondi/delimitMate.git'

"Snipmate
Plugin 'msanders/snipmate.vim.git'

"Syntax highlight
Plugin 'plasticboy/vim-markdown.git'

"Colorscheme
Plugin 'git://github.com/altercation/vim-colors-solarized.git'
Plugin 'tomasr/molokai.git'
if has("gui_running")
  set guioptions+=TRrLlb
  set guioptions-=TRrLlb
  set gfn=Monaco\ 10
  "let g:molokai_original = 1
  set background=dark
  colorscheme molokai
else
  colorscheme zellner
  set background=dark
endif

"(HT|X)ML
Plugin 'tpope/vim-ragtag.git'
Plugin 'rstacruz/sparkup.git', {'rtp': 'vim/'}
let g:user_emmet_leader_key=','
Plugin 'mattn/emmet-vim'

"Git
Plugin 'tpope/vim-fugitive.git'
Plugin 'tpope/vim-git.git'

"Programming languages
Plugin 'vim-scripts/OmniCppComplete.git'
Plugin 'vim-scripts/javacomplete.git'
Plugin 'rosstimson/scala-vim-support.git'
"for clojure
Plugin 'vim-scripts/VimClojure.git'
"for groovy
Plugin 'vim-scripts/groovy.vim'
" elixir
Plugin 'slashmili/alchemist.vim'
Plugin 'elixir-editors/vim-elixir'

"Python realted
Plugin 'kevinw/pyflakes.git'
Plugin 'git://github.com/kevinw/pyflakes-vim.git'
Plugin 'cburroughs/pep8.py.git'
Plugin 'vim-scripts/pep8.git'
let g:pep8_map='<leader>8'

Plugin 'alfredodeza/pytest.vim.git'
Plugin 'fs111/pydoc.vim.git'

"Command-T
Plugin 'wincent/Command-T.git'
let g:CommandTMaxHeight = 15
set wildignore+=*.o,*.obj,.git,*.pyc
noremap <leader>y :CommandTFlush<cr>

"BufExplorer
Plugin 'vim-scripts/bufexplorer.zip.git'
let g:bufExplorerDefaultHelp=0
let g:bufExplorerShowRelativePath=1
let g:bufExplorerFindActive=1
let g:bufExplorerSortBy='name'
map <leader>o :BufExplorer<cr>

"Ack
Plugin 'mileszs/ack.vim.git'
noremap <LocalLeader># "ayiw:Ack <C-r>a<CR>
vnoremap <LocalLeader># "ay:Ack <C-r>a<CR>

"FuzzyFinder
Plugin 'vim-scripts/L9.git'
Plugin 'vim-scripts/FuzzyFinder.git'
nnoremap <leader>fd :FufDir<cr>
nnoremap <leader>ff :FufFile<cr>
nnoremap <leader>fb :FufBuffer<CR>

"Visual Search
Plugin 'bronson/vim-visual-star-search.git'

"mru
Plugin 'vim-scripts/mru.vim.git'
let MRU_Max_Entries = 400
map <leader>m :MRU<CR>

" vundle end, required
call vundle#end()
filetype plugin indent on  "enable loading indent file for filetype/*}}}*/
